# This is a basic workflow to help you get started with Actions

name: CI-CD
 
on:
  
  push:
    branches: [ main ]  
    
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v3
      
     
      - run: echo in progresss 
        name: Docker Login 
      - uses: docker/login-action@v1.14.1
        with: 
          registry: ghcr.io
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PWD }}
          
      - name: Docker Build and Push
        uses: docker/login-action@v1.14.1
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
             dsbrbrasil/rotten-potatoes:latest
             dsbrbrasil/rotten-potatoes:${{ github.run_number }}
